### ISSUE TITLE
Error when trying to submit invoice

### ISSUE THREAD

**Issue by wojosc** [Grynn-GmbH/Swiss-Factur-X-E-invoicing#5]
<img width="888" alt="grafik" src="https://user-images.githubusercontent.com/22279621/123980488-dfb48f80-d9c1-11eb-85e4-7badb00322ea.png">

**Comment by grynn-in** [comment]
Could you add a screen shot of your app versions from help >> about?

**Comment by akazyti** [comment]
The App is working in Frappe Cloud. This can be one  possible reason for error that is  Already an app called factur-x in your ERPNext Installation which may be causing this error.

Our `requirements.txt` already contains fractur-x so having issue of import error is not possible... one help you can do is reproduce error and share your logs

**Comment by wojosc** [comment]
@akashyti @grynn-in @canlann reinstalled on System on which there was no ERPNext Swiss (libracore) installed prior. Works as expected.

System was:
ERPNext: v13.4.1 (version-13)
Frappe Framework: v13.4.1 (version-13)

Thank you guys!

**Comment by wojosc** [comment]
@grynn-in @akashyti  I still can not get it to install on a system on which I had erpnextswiss installed. The System hast v12...

Here are the logs
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 19, in savedocs
    doc.submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 867, in submit
    self._submit()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 856, in _submit
    self.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 326, in _save
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 930, in run_post_save_methods
    self.run_method("on_submit")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1070, in composer
    hooks.append(frappe.get_attr(handler))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1055, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 836, in get_module
    return importlib.import_module(modulename)
  File "/home/frappe/frappe-bench/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/frappe/frappe-bench/apps/swiss_factur_x_e_invoicing/swiss_factur_x_e_invoicing/attach_e_pdf.py", line 3, in <module>
    from facturx import generate_from_binary
ImportError: cannot import name 'generate_from_binary'

Any hints?

**Comment by grynn-in** [comment]
uninstall Swiss E invoicing and Reinstall. As the SwisssERPNext had an older version of Factur-x, the newer version did not get installed. And since it is also a dependent, it is not uninstalled. Kindly remove Swiss E-invoicing as well and install it again. This time check if Factur-x got re-installed or atleast check the version and see if it is the latest version.
